# Generated by Django 4.2.26 on 2025-11-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Recommended landscape images (e.g., 1200×630) for list left-image right-text layouts and detail page header images.', null=True, upload_to='blog/covers/'),
        ),
    ]
