# Generated by Django 4.2.26 on 2025-11-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Cover max size: 10MB', null=True, upload_to='blog/covers/'),
        ),
    ]
