# Generated by Django 4.2.26 on 2025-11-08 15:29

import django.core.validators
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='Subtitle')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('when', models.DateTimeField(help_text='Date and time of the event.', verbose_name='Event Time')),
                ('body', django_summernote.fields.SummernoteTextField(help_text='Event description (supports rich text).', verbose_name='Body / Details')),
                ('cover', models.ImageField(blank=True, help_text='Accepts jpg, jpeg, png, gif, webp.', null=True, upload_to='events/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-when', '-created_at'],
                'indexes': [models.Index(fields=['-when'], name='blog_event_when_4b1d71_idx'), models.Index(fields=['is_published', '-when'], name='blog_event_is_publ_87779a_idx')],
            },
        ),
    ]
