# Generated by Django 4.2.26 on 2025-11-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
