# Generated by Django 4.2.29 on 2026-03-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
