services:
  backend:
    build:
      context: ./drsmith-backend
    env_file:
      - ./drsmith-backend/.env
    command: gunicorn myblog.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "BACKEND_HOST_PORT:8000"
    volumes:
      - ./drsmith-backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    name: drsmith-net

