# Generated by Django 4.2.26 on 2025-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(help_text='Event description (rich editor in admin).', verbose_name='Body / Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
    ]
